global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'minecraft'
    static_configs:
      - targets: ['minecraft:9225']
        labels:
          server_name: 'nsvr-server'
